# Generated by Django 4.2.17 on 2025-02-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carniceria', '0013_ventas_detalle_id_medio_pago_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('id_empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_sucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
