# Generated by Django 4.2.17 on 2025-02-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0014_alter_empresa_email_alter_sucursales_email_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales'),
        ),
    ]
