# Generated by Django 4.2.17 on 2025-02-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_empresa_alter_user_id_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='id_tipo_usuario',
        ),
    ]
