# Generated by Django 4.2.17 on 2025-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_user_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_tipo_usuario',
            field=models.IntegerField(),
        ),
    ]
