# Generated by Django 4.2.17 on 2025-02-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0021_articulo_sucursal_habilitado_articulo_empresa'),
        ('users', '0005_user_is_active_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_sucursal',
        ),
        migrations.CreateModel(
            name='usuario_sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_sucursal',
            },
        ),
        migrations.CreateModel(
            name='usuario_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_empresa',
            },
        ),
    ]
