# Generated by Django 4.2.17 on 2025-02-28 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0023_alter_articulo_sucursal_habilitado'),
        ('users', '0006_remove_user_id_empresa_remove_user_id_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_empresa',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario_empresa',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario_sucursal',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario_sucursal',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales'),
        ),
        migrations.AlterField(
            model_name='usuario_sucursal',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
