# Generated by Django 4.2.17 on 2025-01-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=25)),
            ],
            options={
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('cuit_empresa', models.CharField(max_length=13, unique=True)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='medio_pago',
            fields=[
                ('id_medio_pago', models.AutoField(db_column='id_medio_pago', primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medio_pago',
            },
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='tipo_unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_unidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_unidad',
            },
        ),
        migrations.CreateModel(
            name='ventas_cabecera',
            fields=[
                ('id_cabecera', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('total_general', models.FloatField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.CASCADE, to='carniceria.medio_pago')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'ventas_cabecera',
            },
        ),
        migrations.CreateModel(
            name='ventas_detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=25)),
                ('precio_unitario', models.DecimalField(decimal_places=3, max_digits=25)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_cabecera', models.ForeignKey(db_column='id_cabecera', on_delete=django.db.models.deletion.CASCADE, to='carniceria.ventas_cabecera')),
            ],
            options={
                'db_table': 'ventas_detalle',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=3, default='0', max_digits=25)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_unidad',
            field=models.ForeignKey(db_column='id_unidad', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.tipo_unidad'),
        ),
    ]
