# Generated by Django 4.2.17 on 2025-01-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_compuesto',
            fields=[
                ('id_stock_compuesto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_ingresada', models.DecimalField(decimal_places=3, default='0', max_digits=25)),
                ('peso_inicial', models.DecimalField(decimal_places=3, default='0', max_digits=25)),
                ('peso_actual', models.DecimalField(decimal_places=3, default='0', max_digits=25)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_compuesto',
            },
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='nombre_producto',
            new_name='codigo_articulo',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='peso_promedio',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulos',
            name='variacion_peso',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='stock',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa'),
        ),
        migrations.CreateModel(
            name='articulo_compuesto',
            fields=[
                ('id_compuesto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=100)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.tipo_unidad')),
            ],
            options={
                'db_table': 'articulo_compuesto',
            },
        ),
        migrations.CreateModel(
            name='articulo_composicion',
            fields=[
                ('id_composicion', models.AutoField(primary_key=True, serialize=False)),
                ('proporcion', models.DecimalField(decimal_places=3, default='0', max_digits=25)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias')),
            ],
            options={
                'db_table': 'articulo_composicion',
            },
        ),
    ]
