# Generated by Django 4.2.17 on 2025-01-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0002_stock_compuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
