# Generated by Django 4.2.17 on 2025-01-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0003_alter_stock_fecha_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='fecha_actualizacion',
        ),
    ]
