# Generated by Django 4.2.17 on 2025-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0005_remove_stock_compuesto_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_compuesto',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
