# Generated by Django 4.2.17 on 2025-01-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0007_stock_fecha_actualizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='variacion_peso',
            new_name='variacion',
        ),
    ]
