# Generated by Django 4.2.17 on 2025-01-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0008_rename_variacion_peso_articulos_variacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo_composicion',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='articulo_composicion',
            name='id_compuesto',
            field=models.ForeignKey(db_column='id_compuesto', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulo_compuesto'),
        ),
    ]
