# Generated by Django 4.2.17 on 2025-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0009_remove_articulo_composicion_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_compuesto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
