# Generated by Django 4.2.17 on 2025-01-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0010_alter_articulo_compuesto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_compuesto',
            name='id_compuesto',
            field=models.ForeignKey(db_column='id_compuesto', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulo_compuesto'),
        ),
    ]
