# Generated by Django 4.2.17 on 2025-01-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0011_stock_compuesto_id_compuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_compuesto',
            name='peso_actual',
        ),
        migrations.AddField(
            model_name='stock_compuesto',
            name='peso_venta',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.CreateModel(
            name='articulo_sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'articulo_sucursal',
            },
        ),
    ]
