# Generated by Django 4.2.17 on 2025-02-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0012_remove_stock_compuesto_peso_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_detalle',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.medio_pago'),
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=3, max_digits=25)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
    ]
