# Generated by Django 4.2.17 on 2025-02-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0013_ventas_detalle_id_medio_pago_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='telefono',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ventas_detalle',
            name='id_articulo',
            field=models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos'),
        ),
        migrations.CreateModel(
            name='venta_stock_compuesto',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_cabecera', models.ForeignKey(db_column='id_cabecera', on_delete=django.db.models.deletion.CASCADE, to='carniceria.ventas_cabecera')),
                ('id_compuesto', models.ForeignKey(db_column='id_compuesto', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulo_compuesto')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='carniceria.sucursales')),
            ],
            options={
                'db_table': 'venta_stock_compuesto',
            },
        ),
    ]
