# Generated by Django 4.2.7 on 2025-02-08 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0014_alter_empresa_email_alter_sucursales_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_compuesto',
            name='cantidad_ingresada',
        ),
        migrations.RemoveField(
            model_name='ventas_cabecera',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='ventas_detalle',
            name='id_medio_pago',
        ),
        migrations.AddField(
            model_name='stock_compuesto',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas_cabecera',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.medio_pago'),
        ),
    ]
