# Generated by Django 4.2.17 on 2025-02-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0015_remove_stock_compuesto_cantidad_ingresada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas_cabecera',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.CASCADE, to='carniceria.medio_pago'),
        ),
    ]
