# Generated by Django 4.2.17 on 2025-02-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0016_alter_ventas_cabecera_id_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas_cabecera',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', default=1, on_delete=django.db.models.deletion.CASCADE, to='carniceria.medio_pago'),
        ),
    ]
