# Generated by Django 4.2.7 on 2025-02-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0017_alter_ventas_cabecera_id_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_stock_compuesto',
            name='id_articulo',
            field=models.ForeignKey(db_column='id_articulo', default=89, on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos'),
            preserve_default=False,
        ),
    ]
