# Generated by Django 4.2.7 on 2025-02-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0018_venta_stock_compuesto_id_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_stock_compuesto',
            name='id_compuesto',
        ),
        migrations.AddField(
            model_name='venta_stock_compuesto',
            name='id_stock_compuesto',
            field=models.ForeignKey(db_column='id_stock_compuesto', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.stock_compuesto'),
        ),
        migrations.AddField(
            model_name='venta_stock_compuesto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=25),
            preserve_default=False,
        ),
    ]
