# Generated by Django 4.2.7 on 2025-02-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0019_remove_venta_stock_compuesto_id_compuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_stock_compuesto',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='venta_stock_compuesto',
            name='id_sucursal',
        ),
        migrations.AddField(
            model_name='venta_stock_compuesto',
            name='id_detalle',
            field=models.ForeignKey(db_column='id_detalle', default=1, on_delete=django.db.models.deletion.CASCADE, to='carniceria.ventas_detalle'),
            preserve_default=False,
        ),
    ]
