# Generated by Django 4.2.17 on 2025-02-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0020_remove_venta_stock_compuesto_id_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_sucursal',
            name='habilitado',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='articulo_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=100)),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
            ],
            options={
                'db_table': 'articulo_empresa',
            },
        ),
    ]
