# Generated by Django 4.2.17 on 2025-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0022_alter_articulo_sucursal_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_sucursal',
            name='habilitado',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
