# Generated by Django 4.2.17 on 2025-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0023_alter_articulo_sucursal_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_demo',
            field=models.DateField(null=True),
        ),
    ]
