# Generated by Django 4.2.17 on 2025-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0024_remove_articulos_id_empresa_empresa_fecha_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_empresa',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulo_empresa',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulo_sucursal',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
        migrations.AddField(
            model_name='articulo_sucursal',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=25),
        ),
    ]
