# Generated by Django 4.2.17 on 2025-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0025_articulo_empresa_precio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_empresa',
            name='descripcion',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo_empresa',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.categorias'),
        ),
        migrations.AddField(
            model_name='articulo_empresa',
            name='id_unidad',
            field=models.ForeignKey(db_column='id_unidad', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.tipo_unidad'),
        ),
    ]
