# Generated by Django 4.2.17 on 2025-03-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0026_articulo_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo_empresa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='articulo_empresa',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='articulo_empresa',
            name='id_unidad',
        ),
    ]
