# Generated by Django 4.2.17 on 2025-03-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0027_remove_articulo_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_sucursal',
            name='codigo_articulo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
