# Generated by Django 4.2.17 on 2025-03-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carniceria', '0028_articulo_sucursal_codigo_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo_composicion_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulos')),
                ('id_compuesto', models.ForeignKey(db_column='id_compuesto', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.articulo_compuesto')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', default='1', on_delete=django.db.models.deletion.CASCADE, to='carniceria.empresa')),
            ],
            options={
                'db_table': 'articulo_composicion_empresa',
            },
        ),
    ]
